# Generated by Django 2.0.2 on 2018-06-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='num_like',
        ),
    ]
