# Generated by Django 2.0.2 on 2018-06-19 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 2, 26, 58, 315561)),
        ),
    ]
