# Generated by Django 2.0.2 on 2018-06-19 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180620_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 3, 29, 54, 732685)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
