# Generated by Django 2.0.2 on 2018-06-19 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20180620_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 3, 31, 15, 587785)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
